baseurl: "//il-tuo-url"
languageCode: it
title: Meccatronica101
paginate: 3
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Meccatronica101
  description: "Benvenuti nel blog della Meccatronica!"
  keywords: [Blog, Meccatronica, Sviluppo Software, Progettazione Elettronica, Progettazione Meccanica]
  author: Meccatronica101
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Meccatronica101"
    icon: "images/meccatronica.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Benvenuta/o! \U0001F44B"
    subtitle: "In questo sito parleremo di **Meccatronica** in senso lato. Gli articoli tratteranno i temi pi첫 svariati, dalla progettazione meccanica, a quella elettronica, 
    passando per l'informatica. Nella sezione Sommario troverai una panoramica degli articoli in ordine cronologico, dal pi첫 recente al meno recente. Nella sezione Blogs, invece, 
    sono presenti gli articoli veri e propri. Buona lettura! "
    imageUrl: "images/lampadina.png"
    imageWidth: 300
    imageHeight: 300
    imageTitle: "Tutto nasce da un'idea"
    buttons:
      - name: Sommario
        url: sommario
      - name: Blogs
        url: blogs


  # home-info mode
  homeInfoParams:
    Title: "Benvenuto/a! \U0001F44B"
    Content: "In questo sito parleremo di **Meccatronica** in senso lato. Gli articoli tratteranno i temi pi첫 svariati, dalla progettazione meccanica, a quella elettronica, 
    passando per l'informatica. Nella sezione Sommario troverai una panoramica degli articoli in ordine cronologico, dal pi첫 recente al meno recente. Nella sezione Blogs, invece, 
    sono presenti gli articoli veri e propri. Buona lettura! "



  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:

    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 2
    - identifier: sommario
      name: Sommario
      url: /sommario/
      weight: 1



    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
